### ISSUE TITLE
please add install instructions to the Readme

### ISSUE THREAD

**Issue by rubo77** [gambolputty/wikitable2csv#13]
I would like to use this tool for other mediawiki sites than just wikipedia. So I would install this on my server to change the source accordingly.

**Comment by rubo77** [comment]
I tried 

    $ npm install gulp
    $ gulp
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/wikitable2csv/gulpfile.js:2:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Comment by gambolputty** [comment]
Have you read about the _package.json_ file inside the root directory? Take a look [here](https://docs.npmjs.com/getting-started/using-a-package.json).

You should be fine by running the `npm install` command.

**Comment by rubo77** [comment]
Please accept the PR #15 that adds instructions to the readme
