### ISSUE TITLE
blank page on specific URL

### ISSUE THREAD

**Issue by sloth-101** [gambolputty/wikitable2csv#54]
Seems to be broken atm? 
Only white page when trying to fetch tables, for example 
https://de.wikipedia.org/wiki/Raumschiff_Enterprise/Episodenliste

Tried different browsers.

correction: Actually the tool seems to have an issue with that specific wiki page. others work fine.

edit: same here
https://de.wikipedia.org/wiki/Star_Trek:_Enterprise/Episodenliste

**Comment by pannous** [comment]
Yes, if you look at browser debugger console, you see things like 
```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
wikitable2csv.ggor.de/:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
onloadwff.js:71 Uncaught Error: Attempting to use a disconnected port object
    at onloadwff.js:71:772656
    at onloadwff.js:71:770331
wikitable2csv.ggor.de/:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
/favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'csvText')
    at ResultItem.tsx:18:27
    at ResultItem.tsx:45:33
    at Object.useMemo (react-dom.production.min.js:184:189)
    at t.useMemo (react.production.min.js:25:208)
    at z (ResultItem.tsx:45:19)
    at Eo (react-dom.production.min.js:167:137)
    at Su (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at gs (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
di @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught TypeError: Cannot read properties of undefined (reading 'csvText')
    at ResultItem.tsx:18:27
    at ResultItem.tsx:45:33
    at Object.useMemo (react-dom.production.min.js:184:189)
    at t.useMemo (react.production.min.js:25:208)
    at z (ResultItem.tsx:45:19)
    at Eo (react-dom.production.min.js:167:137)
    at Su (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at gs (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    ```
